export enum explorationTrackOutput {
    NAVIGATION_TILE = "NAVIGATION_TILE",
    PLACE_NAV_TILE = "PLACE_NAV_TILE",
    BROWN_HOUSE = "BROWN_HOUSE",
    TAPESTRY_CARD = "TAPESTRY_CARD",
    VP_FROM_CONQUER = "VP_FROM_CONQUER",
    VP_FROM_BROWN_HOUSE = "VP_FROM_BROWN_HOUSE",
    FIVE_VP = "FIVE_VP",
    VP_FROM_TECH_TRACK = "VP_FROM_TECH_TRACK",
    SPACE_TILE = "SPACE_TILE",
    PLACE_SPACE_TILE = "PLACE_SPACE_TILE",
    PLACE_NAV_TILE_OR_BROWN_HOUSE = "PLACE_NAV_TILE_OR_BROWN_HOUSE",
}